[project]
name = "for-krisco"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "streamlit>=1.49.1",
]

[tool.uv.workspace]
members = [
    "Krisco_mon",
]
